---
- name: Instalación de Elastic
  hosts: elasticsearch
  tasks:
    - name: Instalamos Elasticsearch
      apt:
        name: elasticsearch
        state: present
        update_cache: yes

    - name: Copia del fichero
      ansible.builtin.copy:
        src: elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml

    - name: Reinicio del servicio
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: elasticsearch
