name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
  - name: ansible-syntax-check-action
   uses: Pablohn26/ansible-syntax-check-action@v1.0.0
